# Generated by Django 3.2.9 on 2021-11-24 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('owner', models.CharField(max_length=150)),
                ('dentists', models.IntegerField()),
                ('address', models.CharField(max_length=150, unique=True)),
                ('city', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Openinghours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.TimeField()),
                ('tuesday', models.TimeField()),
                ('wednesday', models.TimeField()),
                ('thursday', models.TimeField()),
                ('friday', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(unique=True)),
                ('latitude', models.FloatField(unique=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentists.dentist')),
            ],
        ),
    ]
