# Generated by Django 3.2.9 on 2021-11-27 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(default=None)),
                ('latitude', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Openinghours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.TimeField(default=None)),
                ('tuesday', models.TimeField(default=None)),
                ('wednesday', models.TimeField(default=None)),
                ('thursday', models.TimeField(default=None)),
                ('friday', models.TimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
                ('dentists', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('coordinate', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dentists.coordinate')),
                ('openinghours', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dentists.openinghours')),
            ],
        ),
    ]
