# Generated by Django 3.2.9 on 2021-12-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0001_squashed_0004_auto_20211202_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='dentists',
            field=models.IntegerField(default=0),
        ),
    ]
