# Generated by Django 3.2.9 on 2021-12-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='timestaken',
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='friday',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='monday',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='thursday',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='tuesday',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='wednesday',
            field=models.TimeField(blank=True),
        ),
    ]
