# Generated by Django 3.2.9 on 2021-12-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0002_auto_20211202_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='timestaken',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
