# Generated by Django 3.2.9 on 2021-12-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0002_alter_dentist_dentists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='dentists',
            field=models.IntegerField(),
        ),
    ]
