# Generated by Django 3.2.9 on 2022-01-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dentists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=300)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dentists.dentist')),
            ],
        ),
    ]
